// Script generated by swake
// Contents of Skeleton.swift:
import Foundation

typealias TaskClosure = [String]? -> Void

func sh(command: String, arguments: [String]?) -> Int32 {
    var task = NSTask()
    task.launchPath = command

    if let arguments = arguments  {
        task.arguments = arguments.map({ $0 as AnyObject})
    }
    
    task.launch()
    task.waitUntilExit()
    return task.terminationStatus
}

var currentNamespace: String? = nil

func namespace(name: String, work: () -> Void) {
    currentNamespace = name
    work()
    currentNamespace = nil
}

var tasks: [String: TaskClosure ] = Dictionary()

func task(name: String, work: TaskClosure) {
    
    var key = name
    if let namespace = currentNamespace {
        key = namespace + ":" + name
    }
    
    tasks[key] = work
}

// Contents of Swakefile: